[project]
name = "analysis"
version = "0.0.1"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = ["src", "test"]
testpaths = ["test"]
