name: checks
on: push

jobs:
  spell:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update packages
        run: sudo apt-get update
      - name: Install spellchecker and dictionary
        run: sudo apt-get install -y hunspell hunspell-en-gb
      - name: Check spelling
        id: spellcheck
        run: |
          echo "numSpellingErrors="$(make -s spell | wc -l) >> $GITHUB_OUTPUT
      - name: Report no errors
        run: echo "::notice title=Spell report::No spelling errors detected"
        if: steps.spellcheck.outputs.numSpellingErrors == 0
      - name: Report errors
        run: echo "::warning title=Spell report::$(steps.spellcheck.outputs.numSpellingErrors) spelling errors detected"
        if: steps.spellcheck.output.numSpellingErrors > 0
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update packages
        run: sudo apt-get update
      - name: Install linter
        run: sudo apt-get install -y chktex
      - name: Run linter
        run: make lint