name: Haskell CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7'
        cabal-version: '3.6'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all



    - name: Set test status to pending
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: "Haskell tests"
        description: "Testing Haskell code"
        state: "pending"
        sha: ${{github.event.pull_request.head.sha || github.sha}}
    - name: Run tests
      id: test
      continue-on-error: true
      run: cabal test all
    - name: Report failure status
      if: ${{ steps.test.outcome == 'failure' }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: "Haskell tests"
        description: "Haskell tests failed"
        state: "failure"
        sha: ${{github.event.pull_request.head.sha || github.sha}}

    - name: Report test failures 
      if: ${{ steps.test.outcome == 'failure' }}
      run: echo -e "::warning title=Haskell test report::Haskell tests failed."

    - name: Report test success status
      if: ${{ steps.test.outcome == 'success' }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: "Haskell tests"
        description: "All Haskell tests pass"
        state: "success"
        sha: ${{github.event.pull_request.head.sha || github.sha}}

    - name: Report test success
      if: ${{ steps.test.outcome == 'success' }}
      run: echo "::notice title=Haskell test report::All tests passed."



